# Generated by Django 5.2.3 on 2025-06-23 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Roll number must be alphanumeric', regex='^[A-Za-z0-9]+$')])),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be 9-15 digits', regex='^\\+?1?\\d{9,15}$')])),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('IT', 'Information Technology'), ('AIML', 'Artificial Intelligence and Machine Learning'), ('CSBS', 'Computer Science and Business Systems')], max_length=10)),
                ('exam_hall_number', models.CharField(max_length=20)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['roll_number'],
            },
        ),
    ]
