# Generated by Django 5.2.3 on 2025-06-23 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
    ]
