# Generated by Django 5.2.3 on 2025-06-23 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20250624_0402'),
    ]

    operations = [
    ]
