# Generated by Django 5.2.3 on 2025-06-23 23:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20250624_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gmail_address',
            field=models.EmailField(blank=True, help_text="Student's Gmail address for exam notifications", max_length=254, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
