# Generated by Django 5.2.3 on 2025-06-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_gmail_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['branch', 'year', 'section', 'roll_number'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(choices=[('A', 'Section A'), ('B', 'Section B'), ('C', 'Section C'), ('D', 'Section D'), ('E', 'Section E')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], default='1', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('branch', 'year', 'section', 'roll_number')},
        ),
    ]
