# Generated by Django 5.2.3 on 2025-06-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_options_student_section_student_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(choices=[('A', 'Section A'), ('B', 'Section B'), ('C', 'Section C'), ('D', 'Section D'), ('E', 'Section E'), ('F', 'Section F'), ('G', 'Section G'), ('H', 'Section H'), ('I', 'Section I'), ('J', 'Section J')], default='A', max_length=1),
        ),
    ]
