# Generated by Django 5.2.3 on 2025-06-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('CSE', 'Computer Science & Engineering (CSE)'), ('CSM', 'Computer Science & Engineering - AI & ML (CSM)'), ('CAI', 'Computer Science & Engineering - Artificial Intelligence (CAI)'), ('CSD', 'Computer Science & Engineering - Data Science (CSD)'), ('CSC', 'Computer Science & Engineering - Cyber Security (CSC)'), ('ECE', 'Electronics and Communication Engineering (ECE)'), ('EEE', 'Electrical and Electronics Engineering (EEE)'), ('MEC', 'Mechanical Engineering (MEC)'), ('CIV', 'Civil Engineering (CIV)')], max_length=10),
        ),
    ]
