# Generated by Django 5.2.3 on 2025-07-03 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_student_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['branch', 'year', 'roll_number'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('branch', 'year', 'roll_number')},
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('CSE', 'Computer Science & Engineering (CSE)'), ('CSM', 'Computer Science & Engineering - AI & ML (CSM)'), ('CAI', 'Computer Science & Engineering - Artificial Intelligence (CAI)'), ('CSD', 'Computer Science & Engineering - Data Science (CSD)'), ('CSC', 'Computer Science & Engineering - Cyber Security (CSC)'), ('ECE', 'Electronics and Communication Engineering (ECE)'), ('EEE', 'Electrical and Electronics Engineering (EEE)'), ('ME', 'Mechanical Engineering (ME)'), ('CIV', 'Civil Engineering (CIV)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='exam_hall_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 9-15 digits', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
    ]
